# Используем официальный образ Python 3.11
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем все файлы из текущей директории в контейнер
COPY . .

# Устанавливаем зависимость termcolor
RUN pip install --no-cache-dir termcolor

# Команда для запуска скрипта при старте контейнера
CMD ["python", "docker_example.py"]